---
# file: ansible-role-prometheus/tasks/main.yaml
- import_role: 
    name: ansible-role-common
  become: false
- import_role: 
    name: geerlingguy.docker
  become: yes

- name: Create prometheus data directory
  file:
    path: /opt/prometheus-data
    state: directory

- name: Create /opt/prometheus-data/
  file:
    path: /opt/prometheus-data
    state: directory
    mode: 777

- name: Generate prometheus config
  template:
    src: prometheus.j2
    dest: /opt/prometheus-data/prometheus.yml
    mode: 644
    force: yes
    backup: yes

- name: Create docker network
  command: docker network create prom-net
  ignore_errors: yes

- name: Check if docker container is running
  shell: docker ps | grep prometheus
  register: container_running
  changed_when: false
  ignore_errors: yes

- name: Check if docker container exist
  command: docker inspect prometheus
  register: container_exist
  changed_when: false
  ignore_errors: yes

- name: Get Prometheus docker image
  shell: docker pull prom/prometheus
  when: not container_exist.rc == 0

- name: Run Prometheus docker container
  shell: docker run --name prometheus --net prom-net -v /opt/prometheus-data:/prometheus --restart unless-stopped --detach prom/prometheus --config.file=/prometheus/prometheus.yml --web.external-url=http://{{ inventory_hostname }} --web.route-prefix="/"
  when: not container_exist.rc == 0

- name: Start existing Prometheus docker container
  shell: docker start prometheus
  when: container_exist.rc == 0 and not container_running.rc == 0
  

# nginx docker
- name: Copy NGINX config
  template:
    src: nginx.conf.j2
    dest: /opt/nginx-data/nginx.conf
  tags: nginx

- name: Generate server certificates
  shell: openssl req -x509 -newkey rsa:4096 -nodes -keyout /opt/nginx-data/server.key -out /opt/nginx-data/server.crt -days 365 -subj "/c=CA/ST=ON/O=name"
  args:
    creates: /opt/nginx-data/server.key
  tags: openssl

- name: Check if NGNIX docker container is running
  shell: docker ps | grep nginx
  register: nginx_container_running
  changed_when: false
  ignore_errors: yes
  tags: nginx

- name: Check if NGINX docker container exist
  command: docker inspect nginx
  register: nginx_container_exist
  changed_when: false
  ignore_errors: yes
  tags: nginx

- name: Get NGINX docker image
  shell: docker pull nginx
  tags: nginx
  when: not nginx_container_exist.rc == 0

- name: Run NGINX docker
  shell: docker run --name nginx --net prom-net -v /opt/nginx-data/nginx.conf:/etc/nginx/nginx.conf:ro -v /opt/nginx-data/:/etc/nginx/ -p 8080:80 -p 8443:443 --restart unless-stopped --detach nginx 
  tags: nginx
  when: not nginx_container_exist.rc == 0

- name: Start existing NGINX docker container
  shell: docker start nginx
  when: nginx_container_exist.rc == 0 and not nginx_container_running.rc == 0
  tags: nginx
