---
# file: ansible-role-prometheus/tasks/main.yaml
- import_role: 
    name: ansible-role-common
- import_role: 
    name: geerlingguy.docker



- name: Create prometheus data directory
  file:
    path: /opt/prometheus-data
    state: directory

- name: Check for custom prometheus configuration
  stat:
    path=files/{{ inventory_hostname }}.prometheus.yml
  register: customConfig
  tags:
    - placeConfig
  delegate_to: 127.0.0.1
  become: no

- name: Copy custom prometheus configuration
  copy: src={{ inventory_hostname }}.prometheus.yml
        dest=/opt/prometheus-data
        force=no
        mode=644
  tags:
    - placeConfig
  when: customConfig.stat.exists

- name: Copy default prometheus configuration
  copy: src=prometheus.yml
        dest=/opt/prometheus-data
        force=no
        mode=644
  tags:
    - placeConfig
  when: not customConfig.stat.exists


- name: Get Prometheus docker image
  shell: docker pull prom/prometheus

- name: Run Prometheus docker container
  shell: docker run --name prometheus -p 9090:9090 -v /opt/prometheus-data:/prometheus-data --restart unless-stopped --detach prom/prometheus --config.file=/prometheus-data/prometheus.yml
