---
# file: ansible-role-prometheus/tasks/main.yaml
- include_role: 
    name: ansible-role-common
- include_role: 
    name: geerlingguy.docker



- name: Create prometheus data directory
  file:
    path: /opt/prometheus-data
    state: directory

- name: Copy default prometheus configuration
  copy: src=prometheus.yml
        dest=/opt/prometheus-data
        force=no
        mode=644
  tags:
    - placeConfig


- name: Get Prometheus docker image
  shell: docker pull prom/prometheus

- name: Run Prometheus docker container
  shell: docker run --name prometheus -p 9090:9090 -v /opt/prometheus-data:/prometheus-data --restart unless-stopped --detach prom/prometheus --config.file=/prometheus-data/prometheus.yml
